name: Tests, Linter and Build

on:
  push:
    branches: [ primary ]
  pull_request:
    branches: [ primary ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run linter
    - run: npm run build
    - run: npm test -- src/
    - run: npm test -- tests/e2e/
      if: ${{ github.event_name == 'push' }}
      env:
        TWITCH_CHANNEL: victor_perin_bot
        TWITCH_BOT_TOKEN: ${{ secrets.TWITCH_BOT_TOKEN }}
        TWITCH_TEST_BOT_TOKEN: ${{ secrets.TWITCH_TEST_BOT_TOKEN }}

    - name: release
      uses: cycjimmy/semantic-release-action@v2.5.0
      if: ${{ github.event_name == 'push' }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
