name: Tests, Linter and Build

on:
  push:
    branches: [ primary ]
  pull_request:
    branches: [ primary ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: testing
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

      env:
        TWITCH_CHANNEL: victor_perin_bot
        TWITCH_BOT_TOKEN: ${{ secrets.TWITCH_BOT_TOKEN }}
        TWITCH_TEST_BOT_TOKEN: ${{ secrets.TWITCH_TEST_BOT_TOKEN }}

    - run: npm install
    - run: npm run linter
    - run: npm test
    - run: npm run build
